my_blogs/urls.py
from django.urls import path
from . import views

app_name = 'my_blogs'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from my_profile import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('my_blogs.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blogs/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    date = models.DateField()

my_profile/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='my_profile/images')
    link = models.URLField(blank=True)

my_blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.http import Http404

def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'my_blogs/blog.html', {'blogs':blogs})

def detail(request, blog_id):
    try:
        blog = get_object_or_404(Blog, pk = blog_id)
        return render(request, 'my_blogs/detail.html', {'blog':blog})
    except Http404:
        return render(request, 'my_blogs/no_detail.html')

my_profile/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'my_profile/home.html', {'projects':projects})

my_blogs/templates/my_blogs/blog.html
<!DOCTYPE html>
<!--link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"-->
{% extends 'my_profile/base.html' %}

{% block basetemplate%}
    <h1 align="center">Satz has written {{blogs.count}} blog{{blogs.count|pluralize}}</h1>

    <meta charset="UTF-8">
    {%for blog in blogs%}
        <a href="{% url 'my_blogs:detail' blog.id %}"><h2>{{blog.title}}</h2></a>
        <h5>{{blog.date|date:'M d Y'}}</h5>
        <p>{{blog.description|truncatechars:100}}</p>
        <br>
    {%endfor%}
{% endblock %}

my_blogs/templates/my_blogs/detail.html
<!--link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"-->
{% extends 'my_profile/base.html' %}

{% block basetemplate%}
<div>
<h1 align="center">{{blog.title}}</h1>
<p>{{blog.description}}</p>
</div>
{% endblock %}

my_blogs/templates/my_blogs/no_detail.html
<!--link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"-->
{% extends 'my_profile/base.html' %}

{% block basetemplate%}

    <h1>Requested page not found</h1>
{% endblock %}

my_profile/templates/my_profile/base - copy.html
<!doctype html>
{% load static%}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/Styles/bootstrap.css">
    <link rel="stylesheet" href="../../static/Styles/vendors/linericon/style.css">
    <link rel="stylesheet" href="../../static/Styles/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/Styles/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="../../static/Styles/vendors/lightbox/simpleLightbox.css">
    <link rel="stylesheet" href="../../static/Styles/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="../../static/Styles/vendors/animate-css/animate.css">
    <link rel="stylesheet" href="../../static/Styles/vendors/popup/magnific-popup.css">
    <link rel="stylesheet" href="../../static/Styles/vendors/flaticon/flaticon.css">
    <!-- main css -->
    <link rel="stylesheet" href="../../static/Styles/css/style.css">
    <link rel="stylesheet" href="../../static/Styles/css/responsive.css">

    <title>Sathish kumar</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'my_profile/Sk_LOGO_blue.jpg' %}" width="50" height="50" class="d-inline-block align-top" alt="Satz's Logo">
            <span width="50" height="50">Sathish kumar</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              
              <li class="nav-item">
                <a class="nav-link" href="{% static 'my_profile/Resume.pdf' %}">Resume</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.linkedin.com/in/link-2-sathish-kumar-d/" target="_blank">LinkedIn</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://twitter.com/Sathish91428810" target="_blank">Twitter</a>
              </li>
              <li>
                <a role="button" href="{% url 'my_blogs:blog' %}" class="btn btn-primary">Blog</a>
              </li>
            </ul>
          </div>
      </div>
  </nav>
  <div class="container">
    {% block basetemplate %}
    {% endblock %}
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

my_profile/templates/my_profile/home.html
<!--link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"-->
{% extends 'my_profile/base.html' %}

{% block basetemplate%}

{% load static%}
<!--div align="center">
    <img src="{% static 'my_profile/SathishPP1.jpg' %}" width="400" height="400">
    <h1>Sathish Portfolio</h1>
    <br>
</div-->

<!--================Home Banner Area =================-->
        <section class="home_banner_area">
           	<div class="container box_1620">
           		<div class="banner_inner d-flex align-items-center">
					<div class="banner_content">
						<div class="media">
							<div class="d-flex">
								<img src="{% static 'my_profile/Sathish.png' %}" alt="">
							</div>
							<div class="media-body">
								<div class="personal_text">
									<h6>Hello Everybody, I am</h6>
									<h3>Sathish kumar</h3>
									<h4>Python django developer</h4>
									<p>Good to see you here, you can find my portfolio in this page. Please go through my page and provide me you suggestions :-).</p>
									<ul class="list basic_info">
										<li><a href="#"><i class="lnr lnr-calendar-full"></i> 18th July, 1985</a></li>
										<li><a href="#"><i class="lnr lnr-phone-handset"></i> +971 55 633 9145</a></li>
										<li><a href="#"><i class="lnr lnr-envelope"></i> Sathishkumard_22@yahoo.co.in</a></li>
										<!--li><a href="#"><i class="lnr lnr-home"></i> Santa monica bullevard</a></li-->
									</ul>
									<ul class="list personal_social">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
{% endblock %}